
# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main
- feature/*

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'sonarqube-3po'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectName=3potest
      sonar.projectKey=3potest